### ISSUE TITLE
Meth bug

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#32]
sometimes it blows up even if it's cooked

**Comment by moher4** [comment]
it still dose it ??? D:

**Comment by Bamarin** [comment]
i got told so, since no one reported yet i did... but i honestly didn't want to try

**Comment by moher4** [comment]
well it is fix i was telling people not to do it, but now it is fix Stephen told me it should be fixed now 
i have not tried using it since then though

**Comment by JDaymon** [comment]
It's fixed as far as I know

**Comment by moher4** [comment]
correction i just did meth and indeed it still dose it, you pickup 1-2 meth and the next is sure to explode i don't know why it dose this but plz fix it already i have lost alot of time and money since the day of it starting to be bugged just revert to the old thing or something for now till you find out what causes it

**Comment by moher4** [comment]
btw here is a demo of what happens http://www.mediafire.com/download/56fwhb4vf933m5z/Meth_Bug_2_!_perpheads_demo_2015-1-23_14-09-55.dem

**Comment by Creepis** [comment]
Cooked meth yesterday, picked up 3 and the last one exploded right infront of my face.It is still not fixed, tbh just revert back to the old v1 meth, less buggier and obviously better.

**Comment by StephenPuffs** [comment]
Fixed now.
